name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  desktop:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2025
          - macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: latest
          cache: true
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          version: 3-latest
          pre-release: false
          build-type: Release
          install-linux-dependencies: true
          cmake-generator: Ninja
      - name: Configure (CMake)
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DDOWNLOAD_DEPENDENCIES=OFF
      - name: Build (CMake)
        run: cmake --build build --config Release --parallel
      - name: Copy dynamic libraries to build output dir (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: cp ${{ steps.sdl.outputs.prefix }}/lib/*.so* build/Release/
      - name: Copy dynamic libraries to build output dir (Windows)
        if: startsWith(matrix.os, 'windows')
        run: cp ${{ steps.sdl.outputs.prefix }}/bin/*.dll build/Release/
      - name: Copy dynamic libraries to build output dir (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: cp ${{ steps.sdl.outputs.prefix }}/lib/*.dylib build/Release/
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}
          path: build/Release/

  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download SDL3 Android Archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh -R libsdl-org/SDL release download release-3.4.4 -p 'SDL3-devel-*-android.zip'
          unzip "SDL3-devel-3.4.4-android.zip" -d android-project/app/libs SDL3-3.4.4.aar
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build gradle project
        run: |
          cd android-project
          ./gradlew assembleDebug
      - name: Upload Build
        uses: actions/upload-artifact@v7
        with:
          name: android
          path: android-project/app/build/outputs/apk/debug/
